# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timo < Formula
  desc "CLI timer to track time on tasks"
  homepage "https://github.com/Egia-Code/homebrew-timo"
  version "0.1.19"
  license "Proprietary (Custom)"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Egia-Code/homebrew-timo/releases/download/v0.1.19/timo_0.1.19_darwin_amd64.tar.gz"
    sha256 "486d4b06a735f3b82b79909550eafe708e29815c589fd3ebf842fc0f976bbd8b"

    def install
      bin.install "timo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Egia-Code/homebrew-timo/releases/download/v0.1.19/timo_0.1.19_darwin_arm64.tar.gz"
    sha256 "683680ad9a8db0db3ca857af5a0a5d1199a2fd8aef93a5df703607ea6e3d811c"

    def install
      bin.install "timo"
    end
  end

  test do
    system "#{bin}/timo", "--version"
  end
end
