# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timo < Formula
  desc "CLI timer to track time on tasks"
  homepage "https://github.com/Egia-Code/homebrew-timo"
  version "0.1.18"
  license "Proprietary (Custom)"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Egia-Code/homebrew-timo/releases/download/v0.1.18/timo_0.1.18_darwin_amd64.tar.gz"
    sha256 "92db419f2d4648033600c55d0b910fdcf6ebe7c90c041e2807d80ac35b107aea"

    def install
      bin.install "timo"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Egia-Code/homebrew-timo/releases/download/v0.1.18/timo_0.1.18_darwin_arm64.tar.gz"
    sha256 "d8c3b222946f1a2d7b3ef8b4b58640e091c55f68d825a1ded5061eb6a9439dc0"

    def install
      bin.install "timo"
    end
  end

  test do
    system "#{bin}/timo", "--version"
  end
end
